backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/img/uploads"

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    format: "json"
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}-{{year}}-{{month}}-{{day}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "services"
    label: "Service"
    format: "json"
    create: true 
    folder: "content/services"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "price (in cents)", name: "price", widget: "number"}
      - {label: "Icon", name: "icon", widget: "image", required: false}


  - name: "testimonials" # Used in routes, e.g., /admin/collections/blog
    label: "Testimonial" # Used in the UI
    format: "json"
    folder: "content/testimonials" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}-{{year}}-{{month}}-{{day}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Picture", name: "picture", widget: "image", required: false}
      - {label: "text", name: "text", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    editor:
         preview: false
    files:
      - file: "content/pages/home.json"
        label: "Home"
        format: "json"
        name: "home"
        fields:
          - label: "Hero"
            name: "hero"
            widget: "object" 
            fields:
              - {label: "Primary Text", name: "primaryText", widget: "string"}
              - {label: "Secondary Text", name: "secondaryText", widget: "string"}
              - {label: "Button Text", name: "button", widget: "string"}
              - {label: "Background", name: "background", widget: "image"}
          - label: "Call to action"
            name: "cta"
            widget: "object" 
            fields:
              - {label: "Primary Text", name: "primaryText", widget: "string"}
              - {label: "Secondary Text", name: "secondaryText", widget: "string"}
          - label: "Testimonials"
            name: "testimonials"
            widget: "object"
            fields:
              - {label: "show", name: 'show', widget: "boolean"}
              - label: "Featured Testimonials"
                name: "testimonials"
                widget: "list"
                fields:
                  - label: "Testimonial"
                    name: "title"
                    widget: "relation"
                    collection: "testimonials"
                    searchFields: ["title"]
                    valueField: "title"
          - label: "Appointment form"
            name: "appointment"
            widget: "boolean"
            default: true
          - label: "Blog Posts"
            name: "blog"
            widget: "object"
            fields:
              - {label: "show", name: 'show', widget: "boolean"}
              - {label: "title", name: 'title', widget: "string", default: "From the blog"}
              - {label: "Sub title", name: 'subtitle', widget: "string", required: false}
              - label: "Featured Posts (pick 3)"
                name: "posts"
                widget: "list"
                fields:
                  - label: "Post"
                    name: "title"
                    widget: "relation"
                    collection: "posts"
                    searchFields: ["title"]
                    valueField: "title"    

