backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/img/uploads"

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    format: "json"
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}-{{year}}-{{month}}-{{day}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "services"
    label: "Service"
    format: "json"
    create: true 
    folder: "content/services"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "price (in cents)", name: "price", widget: "number"}
      - {label: "Icon", name: "icon", widget: "image", required: false}


  - name: "testimonials" # Used in routes, e.g., /admin/collections/blog
    label: "Testimonial" # Used in the UI
    format: "json"
    folder: "content/testimonials" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}-{{year}}-{{month}}-{{day}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    editor:
         preview: false
    files:
      - file: "content/pages/home.json"
        label: "Home"
        format: "json"
        name: "home"
        fields:
          - label: "Hero"
            name: "hero"
            widget: "object" 
            fields:
              - {label: "Primary Text", name: "primary", widget: "string"}
              - {label: "Secondary Text", name: "secondary", widget: "string"}
              - {label: "Button Text", name: "button", widget: "string"}
              - {label: "Background", name: "background", widget: "image"}
          - label: "Follow up"
            name: "followUp"
            widget: "object" 
            fields:
              - {label: "Primary Text", name: "primary", widget: "string"}
              - {label: "Secondary Text", name: "secondary", widget: "string"}

